### ISSUE TITLE
Please add our cvpr23 paper "PolyFormer: Referring Image Segmentation as Sequential Polygon Generation"

### ISSUE THREAD

**Issue by joellliu** [extreme-assistant/CVPR2023-Paper-Code-Interpretation#87]
Hi, 

Can you add our paper "PolyFormer: Referring Image Segmentation as Sequential Polygon Generation"
https://arxiv.org/abs/2302.07387 to the list? It's about vision-language multi-modal learning and instance segmentation. Thank you!

**Comment by extreme-assistant** [comment]
OK
