### ISSUE TITLE
Please add our CVPR-23 paper on knowledge distillation

### ISSUE THREAD

**Issue by Vickeyhw** [extreme-assistant/CVPR2023-Paper-Code-Interpretation#89]
Hi
Can you add our paper "Generic-to-Specific Distillation of Masked Autoencoders " to the list?
Paper: https://arxiv.org/abs/2302.14771  
Code: https://github.com/pengzhiliang/G2SD  
Thank you!

**Comment by extreme-assistant** [comment]
👌
