### ISSUE TITLE
Please add our CVPR2023 paper 

### ISSUE THREAD

**Issue by noahzn** [extreme-assistant/CVPR2023-Paper-Code-Interpretation#90]
Hi, could you add our paper about self-supervised depth estimation?
Title: Lite-Mono: A Lightweight CNN and Transformer Architecture for Self-Supervised Monocular Depth Estimation
Link: https://arxiv.org/abs/2211.13202
Code: https://github.com/noahzn/Lite-Mono

Thanks.

**Comment by extreme-assistant** [comment]
OK
