### ISSUE TITLE
Please add our CVPR 2023 papers on medical image analysis

### ISSUE THREAD

**Issue by MrGiovanni** [extreme-assistant/CVPR2023-Paper-Code-Interpretation#91]
医学影像分析 Medical Image Analysis

1. Label-Free Liver Tumor Segmentation
Paper: https://arxiv.org/pdf/2210.14845.pdf
Code: https://github.com/MrGiovanni/SyntheticTumors

2. Deep Feature In-painting for Unsupervised Anomaly Detection in X-ray Images
Paper: https://arxiv.org/pdf/2111.13495.pdf
Code: https://github.com/tiangexiang/SQUID

Thank you!

**Comment by extreme-assistant** [comment]
OK
