### ISSUE TITLE
Please add our CVPR 2023 paper on Neural Network Structure Design

### ISSUE THREAD

**Issue by JierunChen** [extreme-assistant/CVPR2023-Paper-Code-Interpretation#93]
Title: Run, Don't Walk: Chasing Higher FLOPS for Faster Neural Networks
Paper: https://arxiv.org/abs/2303.03667
Code: https://github.com/JierunChen/FasterNet

**Comment by extreme-assistant** [comment]
OK，your work is excellent,we would like to invite you to share your work on “极市平台”,if you are interest,please contact us(wechat id:fengcall19).

Here are some examples that we present before:
