### ISSUE TITLE
Please add our CVPR 2023 paper on scene text spotting

### ISSUE THREAD

**Issue by ymy-k** [extreme-assistant/CVPR2023-Paper-Code-Interpretation#94]
Hi, could you help to add our CVPR 2023 paper on scene text spotting?
Title: DeepSolo: Let Transformer Decoder with Explicit Points Solo for Text Spotting
Paper: https://arxiv.org/pdf/2211.10772v3.pdf
Code: https://github.com/ViTAE-Transformer/DeepSolo

**Comment by extreme-assistant** [comment]
OK
