### ISSUE TITLE
Please add our CVPR 2023 paper on 3D Semantic Segmentation and Point Cloud

### ISSUE THREAD

**Issue by kts707** [extreme-assistant/CVPR2023-Paper-Code-Interpretation#95]
Hi, could you add our CVPR2023 paper on 3D Semantic Segmentation and Point Cloud? Thanks!

Title: Self-Supervised Image-to-Point Distillation via Semantically Tolerant Contrastive Loss
Link: https://arxiv.org/abs/2301.05709

**Comment by extreme-assistant** [comment]
ok
